name: collector
description: No ads, open-source blood pressure diary app

publish_to: "none"
version: 0.3.0+11

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & routing
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  go_router: ^5.0.1

  # Internationalization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

  # UI-related
  google_fonts: ^3.0.1
  flutter_slidable: ^2.0.0

  # Local persistence
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0

  # Utilities
  path_provider: ^2.0.11
  url_launcher: ^6.1.5
  share_plus: ^4.4.0
  equatable: ^2.0.5
  meta: ^1.8.0

dev_dependencies:
  # Linter
  flutter_lints: ^2.0.1

  # Build runner and generators
  build_runner: ^2.2.1
  isar_generator: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: ic_launcher
  image_path: assets/app_icon.png
  min_sdk_android: 26
  adaptive_icon_foreground: assets/app_icon.png
  adaptive_icon_background: "#8DAFCE"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon.png
