name: collector
description: No ads, open-source blood pressure diary app

publish_to: "none"
version: 0.3.2+14

environment:
  sdk: ">=2.19.0-374.1.beta <3.0.0"
  flutter: ">=3.6.0-0.1.pre"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & routing
  flutter_bloc: ^8.1.1
  get_it:
    git:
      url: git@github.com:sunderee/get-it.git
      ref: 33c8ce89c6ee55f3c12e57c1099e6a9edbb33dec
  go_router: ^5.2.0

  # Internationalization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

  # UI-related
  dynamic_color: ^1.5.4
  flutter_slidable: ^2.0.0

  # Local persistence
  isar: ^3.0.6-dev.0
  isar_flutter_libs: ^3.0.6-dev.0

  # Utilities
  url_launcher: ^6.1.7
  share_plus: ^6.3.0
  equatable:
    git:
      url: git@github.com:sunderee/equatable.git
      ref: c1f00fc332fd6682daa6dc84dd8bf5ab877b2678
  meta: ^1.8.0

dev_dependencies:
  # Linter
  flutter_lints: ^2.0.1

  # Build runner and generators
  build_runner: ^2.3.2
  isar_generator: ^3.0.6-dev.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: ic_launcher
  image_path: assets/app_icon.png
  min_sdk_android: 26
  adaptive_icon_foreground: assets/app_icon.png
  adaptive_icon_background: "#8DAFCE"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon.png
