name: collector
description: No ads, open-source blood pressure diary app

publish_to: 'none'
version: 0.0.2+3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

  # Internationalization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

  # UI-related
  google_fonts: ^3.0.1

  # Local persistence
  hive_flutter: ^1.1.0

  # Utilities
  equatable: ^2.0.3
  path_provider: ^2.0.11
  url_launcher: ^6.1.5
  share_plus: ^4.0.10

dev_dependencies:
  # Linter
  flutter_lints: ^2.0.1

  # Build runner and generator(s)
  build_runner: ^2.2.0
  hive_generator: ^1.1.3

  # Launcher icon generator
  flutter_launcher_icons: ^0.9.3

  # Testing
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: ic_launcher
  ios: false
  image_path: assets/app_icon.png
  adaptive_icon_foreground: assets/app_icon.png
  adaptive_icon_background: "#8DAFCE"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon.png
