name: collector
description: No ads, open-source blood pressure diary app

publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Internationalization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

  # UI-related
  google_fonts: ^3.0.1
  numberpicker:
    path: ./numberpicker

dev_dependencies:
  # Linter
  flutter_lints: ^2.0.1

  # Launcher icon generator
  flutter_launcher_icons: ^0.9.3

  # Testing
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: ic_launcher
  ios: false
  image_path: assets/app_icon.png
  adaptive_icon_foreground: assets/app_icon.png
  adaptive_icon_background: "#FF6978"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon.png
